# Generated by Django 4.1.3 on 2023-02-28 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('telegramApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='skils',
            field=models.ManyToManyField(to='telegramApp.skills', verbose_name='Скилы'),
        ),
    ]
